### ISSUE TITLE
Tab Plus 标签页增强 发现bug

### ISSUE THREAD

**Issue by alwaystest** [dupontjoy/userChromeJS#1]
火狐34.0.5 打开两个窗口，关闭最后打开那个窗口，此时之前打开的窗口不能打开书签工具栏的书签，浏览器控制台显示top is null

**Comment by dupontjoy** [comment]
确实有这个Bug，我也遇到了。由于这个脚本不是我写的，我只是把很多标签相关的小脚本合在一起了。用Singleton.uc.js强制单窗口，应该能解決问题

**Comment by alwaystest** [comment]
收到，Thanks，希望能找到人解决这个问题，我对UC脚本懂的不是太多，没能力修改

**Comment by alwaystest** [comment]
42到47行的代码导致出现这个问题，这段代码也不知道是干啥用的，我注释掉了。
